version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build:
      context: ./api
    ports:
      - "3001:3001"
    volumes:
      - ./api:/api
